Service = "n3-privacy"

[Route]
  LsObject = "/n3-privacy/v0.3.3/list/object"
  Help = "/"
  LsContext = "/n3-privacy/v0.3.3/list/context"
  Update = "/n3-privacy/v0.3.3/update"
  Delete = "/n3-privacy/v0.3.3/delete"
  GetHash = "/n3-privacy/v0.3.3/hash"
  GetID = "/n3-privacy/v0.3.3/id"
  LsUser = "/n3-privacy/v0.3.3/list/user"
  FetchEnfMac = "/n3-privacy/v0.3.3/enforcer/mac"
  Enforce = "/n3-privacy/v0.3.3/enforce"
  Get = "/n3-privacy/v0.3.3/policy"
  LsID = "/n3-privacy/v0.3.3/list/policyid"
  FetchEnfLinux = "/n3-privacy/v0.3.3/enforcer/linux64"
  FetchEnfWin = "/n3-privacy/v0.3.3/enforcer/win64"

[Server]
  IP = "192.168.31.168"
  Port = 1323
  Protocol = "http"

[Access]
  Timeout = 3
