Service = "n3-privacy"

[Route]
  LsID = "/n3-privacy/v0.3.2/list/policyid"
  LsObject = "/n3-privacy/v0.3.2/list/object"
  Update = "/n3-privacy/v0.3.2/update"
  FetchEnfWin = "/n3-privacy/v0.3.2/enforcer/win64"
  Enforce = "/n3-privacy/v0.3.2/enforce"
  GetHash = "/n3-privacy/v0.3.2/hash"
  Help = "/"
  LsContext = "/n3-privacy/v0.3.2/list/context"
  LsUser = "/n3-privacy/v0.3.2/list/user"
  FetchEnfLinux = "/n3-privacy/v0.3.2/enforcer/linux64"
  FetchEnfMac = "/n3-privacy/v0.3.2/enforcer/mac"
  Delete = "/n3-privacy/v0.3.2/delete"
  Get = "/n3-privacy/v0.3.2/policy"
  GetID = "/n3-privacy/v0.3.2/id"

[Server]
  IP = "192.168.31.168"
  Port = 1323
  Protocol = "http"

[Access]
  Timeout = 3
