Log = "~/.[s]/log/[DATE].log"
Path = "/home/qmiao/Desktop/n3/n3-privacy/Server/config/config.toml"
Service = "n3-privacy"
Version = "v0.2.6"

[Storage]
  Tracing = true
  DB = "badger"
  DBPath = "~/.[s]/db/[db]/"

[Loggly]
  Token = "54290728-93e0-425a-a49c-c9e834288026"

[WebService]
  Port = 1323

[Route]
  Update = "/[s]/[v]/update"
  LsID = "/[s]/[v]/list/policyid"
  Enforce = "/[s]/[v]/enforce"
  LsContext = "/[s]/[v]/list/context"
  HELP = "/"
  LsUser = "/[s]/[v]/list/user"
  GetID = "/[s]/[v]/id"
  Get = "/[s]/[v]/policy"
  Delete = "/[s]/[v]/delete"
  GetHash = "/[s]/[v]/hash"
  LsObject = "/[s]/[v]/list/object"

[File]
  EnforcerWin64 = "../../../Enforcer/build/win64/enforcer.exe"
  ClientConfig = "../../../Client/build/linux64/cfg-clt-privacy.toml"
  ClientLinux64 = "../../../Client/build/linux64/client"
  ClientMac = "../../../Client/build/mac/client"
  ClientWin64 = "../../../Client/build/win64/client.exe"
  EnforcerLinux64 = "../../../Enforcer/build/linux64/enforcer"
  EnforcerMac = "../../../Enforcer/build/mac/enforcer"

[Server]
  IP = "[IP]"
  Port = "[port]"
  Protocol = "http"

[Access]
  Timeout = 3
