Path = "/home/qmiao/Desktop/n3/n3-privacy/Server/config/config.toml"
Service = "n3-privacy"
Version = "v0.2.9"
Log = "~/.[s]/log/[DATE].log"

[Storage]
  DB = "badger"
  DBPath = "~/.[s]/db/[db]/"

[Loggly]
  Token = "54290728-93e0-425a-a49c-c9e834288026"

[WebService]
  Port = 1323

[Route]
  LsID = "/[s]/[v]/list/policyid"
  Update = "/[s]/[v]/update"
  Get = "/[s]/[v]/policy"
  GetID = "/[s]/[v]/id"
  GetHash = "/[s]/[v]/hash"
  LsContext = "/[s]/[v]/list/context"
  Enforce = "/[s]/[v]/enforce"
  HELP = "/"
  LsObject = "/[s]/[v]/list/object"
  LsUser = "/[s]/[v]/list/user"
  Delete = "/[s]/[v]/delete"

[Server]
  IP = "[IP]"
  Port = "[port]"
  Protocol = "http"

[Access]
  Timeout = 3
