Path = "/home/qmiao/Desktop/n3/n3-privacy/Server/config/config.toml"
LogFile = "./N3-PRIVACY-[DATE].log"
ServiceName = "N3-PRIVACY"

[Storage]
  DataBase = "badger"
  BadgerDBPath = "/var/tmp/n3-privacy/badger/"
  Tracing = true

[WebService]
  Port = 1323
  Service = "policy-service"
  Version = "v0.2.1"

[Route]
  HELP = "/"
  GetID = "/[s]/[v]/id"
  GetHash = "/[s]/[v]/hash"
  Get = "/[s]/[v]/policy"
  Update = "/[s]/[v]/update"
  Delete = "/[s]/[v]/delete"
  LsID = "/[s]/[v]/list/policyid"
  LsUser = "/[s]/[v]/list/user"
  LsContext = "/[s]/[v]/list/context"
  LsObject = "/[s]/[v]/list/object"
  Enforce = "/[s]/[v]/enforce"

[File]
  ClientLinux64 = "../../../Client/build/linux64/client"
  ClientMac = "../../../Client/build/mac/client"
  ClientWin64 = "../../../Client/build/win64/client.exe"
  ClientConfig = "../../../Client/build/linux64/cfg-clt-privacy.toml"
  EnforcerLinux64 = "../../../Enforcer/build/linux64/enforcer"
  EnforcerMac = "../../../Enforcer/build/mac/enforcer"
  EnforcerWin64 = "../../../Enforcer/build/win64/enforcer.exe"

[Server]
  Protocol = "http"
  IP = "[IP]"
  Port = "[PORT]"

[Access]
  Timeout = 3
