Log = "~/.[s]/log/[DATE].log"
Path = "/home/qmiao/Desktop/n3/n3-privacy/Server/config/config.toml"
Service = "n3-privacy"
Version = "v0.2.2"

[Storage]
  DB = "badger"
  DBPath = "~/.[s]/db/[db]/"
  Tracing = true

[Loggly]
  Token = "54290728-93e0-425a-a49c-c9e834288026"

[WebService]
  Port = 1323

[Route]
  Delete = "/[s]/[v]/delete"
  Enforce = "/[s]/[v]/enforce"
  Get = "/[s]/[v]/policy"
  GetHash = "/[s]/[v]/hash"
  GetID = "/[s]/[v]/id"
  HELP = "/"
  LsContext = "/[s]/[v]/list/context"
  LsID = "/[s]/[v]/list/policyid"
  LsObject = "/[s]/[v]/list/object"
  LsUser = "/[s]/[v]/list/user"
  Update = "/[s]/[v]/update"

[File]
  ClientConfig = "../../../Client/build/linux64/cfg-clt-privacy.toml"
  ClientLinux64 = "../../../Client/build/linux64/client"
  ClientMac = "../../../Client/build/mac/client"
  ClientWin64 = "../../../Client/build/win64/client.exe"
  EnforcerLinux64 = "../../../Enforcer/build/linux64/enforcer"
  EnforcerMac = "../../../Enforcer/build/mac/enforcer"
  EnforcerWin64 = "../../../Enforcer/build/win64/enforcer.exe"

[Server]
  Protocol = "http"
  IP = "[IP]"
  Port = "[port]"

[Access]
  Timeout = 3
