Path = "/home/qmiao/Desktop/n3/n3-privacy/Server/config.toml"
Service = "n3-privacy"

[Route]
  GetID = "/n3-privacy/v0.3.0/id"
  LsContext = "/n3-privacy/v0.3.0/list/context"
  LsID = "/n3-privacy/v0.3.0/list/policyid"
  Update = "/n3-privacy/v0.3.0/update"
  Enforce = "/n3-privacy/v0.3.0/enforce"
  Get = "/n3-privacy/v0.3.0/policy"
  GetHash = "/n3-privacy/v0.3.0/hash"
  LsUser = "/n3-privacy/v0.3.0/list/user"
  Delete = "/n3-privacy/v0.3.0/delete"
  HELP = "/"
  LsObject = "/n3-privacy/v0.3.0/list/object"

[Server]
  Port = 1323
  Protocol = "http"
  IP = "192.168.31.168"

[Access]
  Timeout = 3
