Path = ""
ErrLog = "./errorlog.txt"
JMPath = "../../JSON-Mask/build/Linux64/jm"
JQPath = "../../JSON-Mask/build/Linux64/jq"

[WebService]
  Port = 1323
  Version = "0.1.0"

[Route]
  GetID = "/policy-server/#/id"
  GetHash = "/policy-server/#/hash"
  Get = "/policy-server/#/policy"
  Update = "/policy-server/#/update"
  GetJM = "/policy-server/#/jm"
  GetJQ = "/policy-server/#/jq"
  
[Storage]
  DataBase = "badger" # "map" / "badger" / ...
  MetaPath = "/var/tmp/n3-privacy/meta/"
  BadgerDBPath = "/var/tmp/n3-privacy/badger/" # "./data/badger/"