Path = ""
ErrLog = "./elog.txt"
JMPath = "../../JSON-Mask/build/Linux64/jm"
JQPath = "../../JSON-Mask/build/Linux64/jq"

[WebService]
  Port = 1323
  Version = "0.1.0"

[Route]
  Peek = "/policy-server/#/peek"
  Get = "/policy-server/#/get"
  Update = "/policy-server/#/update"
  GetJM = "/policy-server/#/jm"
  GetJQ = "/policy-server/#/jq"
  